### ISSUE TITLE
lz4.armhf not found

### ISSUE THREAD

**Issue by Drsheppard01** [mgord9518/shappimage#1]
1. Open the make_runtime.sh
2. Downloading file https://github.com/mgord9518/squashfuse-zig/releases/download/continuous/squashfuse_lz4.armhf (armhf not available)

**Comment by mgord9518** [comment]
Thanks for the report! I've been unable to build squashfuse-zig yet for armhf due to some atomic instruction issue, so as a temporary fix (7e49058eaa37c0aa257cc6232ee9d9490ff0a3f4) I've simply refactored `make_runtime.sh` and disabled support for armhf until I can get it working. x86_64  and aarch64 builds should both work correctly

**Comment by mgord9518** [comment]
Should be fixed by 439a7b8a91af61fe3f44e93e3d056e8d0ca8a943
