### ISSUE TITLE
Error when launch shimg

### ISSUE THREAD

**Issue by Drsheppard01** [mgord9518/shappimage#7]
When i launch file i has this output

`Thorium.shImg: line 206: /run/user/1000/1000-shImg-squashfs-lz4-x86_64: unable to run binary file: Executable file format error
failed to mount bundle image! see error message above`

Before actions:

1. mksquashfs 
2. make runtime
3. cat $HOME/shappimage/runtime2 $HOME/Thorium.sqfs > Thorium.shImg
4. chmod +x and launch this

Line 206: ```"$temp_exe" "$1" "$2" -o offset=$3```

**Comment by mgord9518** [comment]
After building the runtime, use the one labeled `runtime-[COMPRESSION ALGORITHM]-[ARCHITECTURE]` instead, I'll edit the build script to remove these confusingly named temporary files, I'll also leave this open for others to see until I can get it fixed

**Comment by mgord9518** [comment]
I've tweaked `make_runtime.sh`, let me know if this fixes the issue

**Comment by Drsheppard01** [comment]
Thx, now it's worked for me, but by default it hasn't execute permission's. Can You add chmod +x in script for users can execute this instead granted permissions before

Sometimes I forget to be polite and just grateful. Thank You for your work. I am proud of you, you are making an invaluable contribution to Linux application packaging

**Comment by mgord9518** [comment]
Unfortunately there's no way for the script to do that since you're generating the shImg after running the script (although you should only have to do it once since overwrites will preserve permissions)

Eventually I'll make an actual tool (probably using Zig) that will completely create an AppImage using the AppDir, and that'll be able to add the executable bit
